# Generated by Django 5.2.11 on 2026-02-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
